// Central configuration for the Urbium (eurobydleni.cz) sync.
// Credentials come only from environment variables (GitHub Actions Secrets) —
// never hardcode them here.

// Overridable via env for local testing against a mock server; production
// always uses the real Urbium endpoint.
const BASE_URL = process.env.URBIUM_BASE_URL || "https://eurobydleni.cz/download/full_list_xml.php";

export const URBIUM_USERNAME = process.env.URBIUM_USERNAME || "";
export const URBIUM_PASSWORD = process.env.URBIUM_PASSWORD || "";

export function listUrl() {
  return `${BASE_URL}?username=${encodeURIComponent(URBIUM_USERNAME)}&password=${encodeURIComponent(URBIUM_PASSWORD)}`;
}

export function detailUrl(propertyId) {
  return `${listUrl()}&property_id=${encodeURIComponent(propertyId)}`;
}

export const SITE_BASE_URL = "https://www.romanareality.cz";

export const REQUEST_TIMEOUT_MS = 20_000;
export const REQUEST_MAX_RETRIES = 3;
export const REQUEST_RETRY_BASE_DELAY_MS = 1_000; // 1s, 3s, 9s backoff

// Urbium asks for calls to the detail endpoint to be spaced out rather than
// looped — this is the delay between consecutive detail calls within one run.
export const DETAIL_CALL_DELAY_MS = Number(process.env.URBIUM_DETAIL_DELAY_MS ?? 60_000);
export const DETAIL_CALL_JITTER_MS = Number(process.env.URBIUM_DETAIL_DELAY_MS ?? 0) > 0 ? 0 : 10_000;

// Cap on how many queue actions (insert/update/deactivate) are processed in a
// single workflow run. Anything beyond this rolls over to the next scheduled
// run via the persisted pendingActions queue.
export const MAX_ACTIONS_PER_RUN = 20;

// How many consecutive detail-fetch failures in one run before aborting —
// treated as a likely Urbium-side outage rather than one-off bad data.
export const FAILURE_ABORT_THRESHOLD = 3;

// How many active properties to feature on the homepage grid.
export const MAX_HOMEPAGE_CARDS = 12;

export const USER_AGENT =
  "RomanaRealityUrbiumSync/1.0 (+https://www.romanareality.cz; contact: romana@romanareality.cz)";

export const STATE_FILE = new URL("../data/urbium-properties.json", import.meta.url).pathname;
export const IMAGES_DIR = new URL("../images/nemovitosti/", import.meta.url).pathname;
export const PLACEHOLDER_IMAGE = "images/nemovitost-placeholder.svg";

export const INDEX_HTML = new URL("../index.html", import.meta.url).pathname;
export const SITEMAP_XML = new URL("../sitemap.xml", import.meta.url).pathname;

export const LISTINGS_MARKER_START =
  "<!-- URBIUM:LISTINGS:START — auto-generated by scripts/sync-urbium.mjs, do not edit by hand -->";
export const LISTINGS_MARKER_END = "<!-- URBIUM:LISTINGS:END -->";

export const SITEMAP_MARKER_START =
  "<!-- URBIUM:URLS:START — auto-generated by scripts/sync-urbium.mjs, do not edit by hand -->";
export const SITEMAP_MARKER_END = "<!-- URBIUM:URLS:END -->";
